// Espejo del catalogo de items de auditorias del frontend
// (src/modules/audits/services/auditsService.ts: CAMION_ITEMS / HIDROGUA_SECTIONS).
// Se duplica aca porque el backend no comparte codigo con el frontend en este
// proyecto — si se agregan/cambian items alla, hay que actualizar esto tambien.

export interface CatalogItem {
  code: string
  desc: string
}

export const CAMION_ITEMS: CatalogItem[] = [
  { code: 'A-01', desc: 'Nivel de Aceite' },
  { code: 'A-02', desc: 'Nivel de Líquido de Freno' },
  { code: 'A-03', desc: 'Nivel de Refrigerante/Anticongelante' },
  { code: 'A-04', desc: 'Nivel de Líquido de Dirección' },
  { code: 'A-05', desc: 'Motor — Pérdidas' },
  { code: 'A-06', desc: 'Faros Luz (Alta / Baja / Posición)' },
  { code: 'A-07', desc: 'Luces de Guiños (Delanteros / Traseros)' },
  { code: 'A-08', desc: 'Luces Stop / Luz y Alarma de Retroceso' },
  { code: 'A-09', desc: 'Bandas Retroreflectivas / Vel. Máxima' },
  { code: 'A-10', desc: 'Tapa del Tanque de Combustible' },
  { code: 'A-11', desc: 'Dirección / Tren Delantero / Amortiguación' },
  { code: 'A-12', desc: 'Parabrisas' },
  { code: 'A-13', desc: 'Limpiaparabrisas (Escobilla / Zorrino)' },
  { code: 'A-14', desc: 'Ventanas / Estado / Funcionamiento / Cierre' },
  { code: 'A-15', desc: 'Batería, Estado, Anclaje, Protección Externa' },
  { code: 'A-16', desc: 'Espejos / Estado / Cantidad / Funcionamiento' },
  { code: 'A-17', desc: 'Chapa de Patente Visible Del. y Post.' },
  { code: 'A-18', desc: 'Identificación Empresa / Logo / Nº Interno' },
  { code: 'A-19', desc: 'Cortinas / Estado / Cantidad / Limpieza' },
  { code: 'A-20', desc: 'Bloqueo de Diferencial / Freno de Motor' },
  { code: 'A-21', desc: 'Luces Interior (Tablero / Cabina)' },
  { code: 'A-22', desc: 'Parasoles / Estado / Cantidad' },
  { code: 'A-23', desc: 'Indicador de Combustible (Tablero)' },
  { code: 'A-24', desc: 'Asientos / Apoyacabezas' },
  { code: 'A-25', desc: 'Cinturones de Seguridad Chofer/Acomp.' },
  { code: 'A-26', desc: 'Bocina' },
  { code: 'A-27', desc: 'Velocímetro / Odómetro' },
  { code: 'A-28', desc: 'Calefacción / Aire Acondicionado' },
  { code: 'A-29', desc: 'Toma de Aire Interna / Pistola Sopletear' },
  { code: 'A-30', desc: 'Reflectores Traseros Auxiliares / Cantidad / Estado' },
  { code: 'A-31', desc: 'Busca Huellas / Rompe Niebla' },
  { code: 'A-32', desc: 'Criques, Llaves — Tacos — Balizas Reglamentarias' },
  { code: 'A-33', desc: 'Puertas / Cerradura' },
  { code: 'A-34', desc: 'Estado de Limpieza Interior' },
  { code: 'A-35', desc: 'Sistema de Frenos / Freno de Mano' },
  { code: 'A-36', desc: 'Botiquín Prim. Auxilios / Chaleco Reflectivo' },
  { code: 'A-37', desc: 'Extintores 1 kg — 5 kg — 10 kg Vencimiento' },
  { code: 'A-38', desc: 'Fijación de Extintor dentro de Cabina' },
  { code: 'A-39', desc: 'Equipo de Radio (Funcionamiento)' },
  { code: 'A-40', desc: 'Paragolpes (Delantero / Traseros)' },
  { code: 'A-41', desc: 'Tacógrafo / Funcionamiento / Modelo' },
  { code: 'A-42', desc: 'Barra de Remolque / Perno de Remolque' },
  { code: 'A-43', desc: 'Diferencial / Pérdidas / Temperatura / Ruidos' },
  { code: 'A-44', desc: 'Cardán / Crucetas / Manchón Centro Cardán' },
  { code: 'A-45', desc: 'Alineación y Balanceo' },
  { code: 'A-46', desc: 'Estado de Cubiertas' },
  { code: 'A-47', desc: 'Rueda de Auxilio / Soporte Rueda de Auxilio' },
  { code: 'A-48', desc: 'Espárragos y Tuercas de Ruedas' },
  { code: 'A-49', desc: 'Plato de Enganche / Tijera' },
  { code: 'A-50', desc: 'Llave de Cabina / Crique / Traba de Cabina' },
  { code: 'A-51', desc: 'Toma de Aire Externa' },
  { code: 'A-52', desc: 'Estado de Mangueras y Acoples de Aire' },
  { code: 'A-53', desc: 'Estado del Pulmón Aire de Freno (Fuelle)' },
  { code: 'A-54', desc: 'Cadena Cond. Climáticas Adversas Fís./Líq.' },
  { code: 'A-55', desc: 'Caja de Herramientas del Equipo' },
  { code: 'A-56', desc: 'Grasera' },
  { code: 'A-57', desc: 'Bomba de Toma de Fuerza' },
  { code: 'A-58', desc: 'Estado Mangueras Hidráulicas / Fugas' },
]

export const HIDROGUA_ITEMS: CatalogItem[] = [
  { code: 'C-01', desc: 'Ausencia de golpes severos, torceduras o rajaduras (Pluma)' },
  { code: 'C-02', desc: 'Suavidad del accionamiento hidráulico de todos sus tramos (Pluma)' },
  { code: 'C-03', desc: 'Cartelería de modelo, marca, carga máxima y certificación vigente (Pluma)' },
  { code: 'C-04', desc: 'Ausencia de rajaduras, deformaciones significativas y/o desgastes excesivos (Pluma)' },
  { code: 'C-05', desc: 'Seguro y resorte en buen estado y funcionando correctamente (Pluma)' },
  { code: 'C-06', desc: 'Sin marcas de modificación o reparación, amolado, soldadura, pintura nueva (Gancho)' },
  { code: 'C-07', desc: 'Funcionamiento adecuado de crapodina, giro con carga sin trabarse (Gancho)' },
  { code: 'C-08', desc: 'Presencia de precinto de certificación de Gancho y Grilletes (Gancho)' },
  { code: 'C-09', desc: 'Marca, Modelo, Capacidad, en relieve legibles y en buen estado (Gancho)' },
  { code: 'C-10', desc: 'Ausencia de pérdida de aceite hidráulico, estado de empaquetadura y buje (Cilindros)' },
  { code: 'C-11', desc: 'Pernos, seguros, Alemites, ruidos o golpes cuando opera (Cilindros)' },
  { code: 'C-12', desc: 'Horquilla sin rajaduras, deformaciones, o reparaciones sin certificar (Cilindros)' },
  { code: 'C-13', desc: 'Vástagos Rectos, sin deformaciones, golpes o rayones visibles (Cilindros)' },
  { code: 'C-14', desc: 'Válvula de Seguridad, No se baja el Pistón solo, sin pérdidas o golpes (Cilindros)' },
  { code: 'C-15', desc: 'Suavidad en el movimiento (Superestructura giratoria)' },
  { code: 'C-16', desc: 'Ausencia de ruidos de cremallera o crapodina cuando opera, engrase (Superestructura giratoria)' },
  { code: 'C-17', desc: 'Pérdidas de aceite en Cremalleras o base de la estructura (Superestructura giratoria)' },
  { code: 'C-18', desc: 'Se extienden correctamente al 100%, poseen marca de final de carrera (Estabilizadores)' },
  { code: 'C-19', desc: 'Sin Golpes, Pérdidas, Rajaduras o marcas de reparación sin certificar (Estabilizadores)' },
  { code: 'C-20', desc: 'Placas de expansión adecuadas al equipo en capacidad y cantidad (Estabilizadores)' },
  { code: 'C-21', desc: 'Nivel de burbuja para estabilizar correctamente (Estabilizadores)' },
  { code: 'C-22', desc: 'Chasis sin Rajaduras o Deformaciones, Anclaje de Equipo Ajustado (Chasis/anclaje/comandos)' },
  { code: 'C-23', desc: 'Suavidad de accionamiento, Nivel de firmeza, posición adecuada (Chasis/anclaje/comandos)' },
  { code: 'C-24', desc: 'Nivel de aceite, visor, fugas en Mangueras, acoples, tapa del Depósito (Chasis/anclaje/comandos)' },
  { code: 'C-25', desc: 'Iluminación auxiliar, adecuada en cantidad y calidad (Chasis/anclaje/comandos)' },
  { code: 'C-26', desc: 'Extintor, estado, anclaje adecuado — Tipo/Cap/Venc (Chasis/anclaje/comandos)' },
  { code: 'C-27', desc: 'Tabla de carga, cartelería de advertencia del Riesgo (Chasis/anclaje/comandos)' },
  { code: 'C-28', desc: 'Alarma indicadora de accionamiento de Hidrogrúa (Chasis/anclaje/comandos)' },
  { code: 'C-29', desc: 'Especificar (Otros)' },
]
